version: 1.0.{build}

image: 
  - Visual Studio 2019
  - Ubuntu
  - macOS

before_build:
  - nuget restore

artifacts:
  - path: ReflectionReader/bin/Debug/netcoreapp3.1/
    name: ReflectionReader
    type: zip
